"""unique email username

Revision ID: ca75a6b5c6d5
Revises: 9a1f53dec924
Create Date: 2020-06-21 18:51:46.191011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca75a6b5c6d5'
down_revision = '9a1f53dec924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email_username', 'users', ['email', 'username'])
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_constraint('uq_users_email_username', 'users', type_='unique')
    # ### end Alembic commands ###
